{% set name = "coloraide" %}
{% set version = "4.6" %}
{% set sha256 = "e41ce60210476d88e18093a32973a2f046bc3a4e778871bb14e7f2f817f88f6a" %}
{% set build_number = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/coloraide-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: {{ build_number }}

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=0.21.1
    - pip
  run:
    - python >={{ python_min }}
    - typing-extensions

test:
  imports:
    - coloraide
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/coloraide/
  summary: A color library for Python.
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  doc_url: https://facelessuser.github.io/coloraide/
  dev_url: https://github.com/facelessuser/coloraide

extra:
  recipe-maintainers:
    - apcamargo
    - seantycho
    - mfisher87
    - rushirajnenuji
