{% set name = "coloraide" %}
{% set version = "8.11.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 045315611aaf1346535a33b4ee974d04c3ec5c5d257a35beccbe0c6c7768dd90

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv"

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=0.21.1
    - pip
  run:
    - python >={{ python_min }}
    - typing-extensions

test:
  imports:
    - coloraide
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/coloraide/
  summary: A color library for Python.
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  doc_url: https://facelessuser.github.io/coloraide/
  dev_url: https://github.com/facelessuser/coloraide

extra:
  recipe-maintainers:
    - apcamargo
    - seantycho
    - mfisher87
    - rushirajnenuji
